live reload pull requests
substancelab/pullhub pull request #31
Opened 2016-11-18 12:07 UTC by jakobdamjensen

Så reloader den også indholdet af siden uden at man skal refreshe pull requests siden

closes #27

2016-11-18 13:44 UTC, olepalm commented on web/services/github_api.ex
> +    |> convert_pull_requests_to_stucts
`convert_pull_requests_to_stucts`, skulle det ikke være `convert_pull_requests_to_structs` ?

Ellers, hvad er en stuct?

2016-11-18 13:45 UTC, jakobdamjensen commented on web/services/github_api.ex
> +    |> convert_pull_requests_to_stucts
jo da :)

2016-11-18 13:47 UTC, koppen requested changes

2016-11-18 13:47 UTC, koppen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +  alias Pullhub.StoredPullRequests
Lad os holde det alfabetisk, så det er til at overskue, hvad der er alias'et.

2016-11-18 13:47 UTC, koppen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +      |> Repo.all
Hvad gør `Repo.all`, når den modtager et argument? Jeg ville tro, den altid returnerede alle `Repo`s

2016-11-18 13:47 UTC, koppen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +
Lidt rigeligt whitespace

2016-11-18 13:47 UTC, koppen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +      |> Repo.all
Faktisk er jeg nok ikke helt med på, hvad `StoredPullRequests.pull_requests/1` returnerer, så jeg er ikke med på, hvad der sker her.

2016-11-18 13:47 UTC, koppen commented on lib/pullhub/pull_requests_sync.ex
> +  alias Pullhub.StoredPullRequests
🔤

2016-11-18 13:47 UTC, koppen commented on lib/pullhub/pull_requests_sync.ex
> +    |> Repository.preload_user
Burde den her kæde bo i `Repository` under et eller andet navn?

2016-11-18 13:47 UTC, koppen commented on lib/pullhub/stored_pull_requests.ex
> +  alias Pullhub.Repo
🔤

2016-11-18 13:47 UTC, koppen commented on web/models/user.ex
> +    (from u in Pullhub.User, where: not(is_nil(u.github_token)))
`user` frem for `u`?

2016-11-18 13:47 UTC, koppen commented on web/static/js/channels/pull_request_channel.js
> +    setTimeout(updateList, 120000)
Hvorfor er det her nødvendigt, når data bliver pushet ud via channel?

2016-11-18 13:49 UTC, jakobdamjensen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +      |> Repo.all
Den returnerer et query som man giver til Repo.all. I stel med scopes i Rails - men det bliver først afviklet når man sender det afsted til et Repo

2016-11-18 13:50 UTC, jakobdamjensen commented on web/static/js/channels/pull_request_channel.js
> +    setTimeout(updateList, 120000)
fordi vi lige nu ikke fetcher fra github på noget tidspunkt hvis der ikke bliver bedt om det eksplicit. 

Når webhooks bliver implementeret forsvinder de her timere

2016-11-18 13:52 UTC, jakobdamjensen commented on lib/pullhub/pull_requests_sync.ex
> +    |> Repository.preload_user
Måske :)

2016-11-18 14:07 UTC, koppen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +      |> Repo.all
Så `User.all` fungerer mere som en slags `User.where`?

2016-11-25 07:56 UTC, jakobdamjensen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +      |> Repo.all
Der er ikke noget User.all. Man går altid igennem et Repo. Det er forvirrende da vi også har kaldt de repositories vi persistere for Repository. Det skal helt sikkert ændres :)

Men man laver en query og sender den til Repo.all, Repo.get, Repo.update eller Repo.create (eller lign. funktioner)

2016-11-25 08:27 UTC, koppen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +      |> Repo.all
Right, sorry, jeg mente `Repo.all`; det er lidt ala `Repo.where` i at den tager en query og returnerer nogle data.

2016-11-25 08:44 UTC, jakobdamjensen commented on lib/pullhub/broadcasters/pull_requests_broadcaster.ex
> +      |> Repo.all
Yep

2016-11-25 10:49 UTC, koppen approved these changes

2016-11-25 10:49 UTC, merged